version: "3" 

services: 
  nginxproxy: 
    depends_on: 
      - nginx 
      - apache 
    image: nginx 
    ports: 
      - "8080:8080" 
      - "8081:8081" 
    restart: always
    volumes: 
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf" 
  
  nginx: 
    image: nginx 
    restart: always 
    
  apache: 
    image: httpd:2.4.46 
    restart: always
